import type { StorageAdapter } from '@/data/storage';
import type { Alert } from '@/data/models';
import { BaseRepository } from './BaseRepository';

const COLLECTION = 'alerts';

const DATE_FIELDS: ReadonlyArray<keyof Alert> = ['alertDate'];

/**
 * AlertRepository — persistence for Alert entities.
 *
 * Alerts are generated by `scheduleAlerts` after a purchase with a warranty
 * or return window is saved (steps 17–20 of the Add Purchase sequence). The
 * Alerts page queries by `isRead === false` and by `purchaseId`.
 */
export class AlertRepository extends BaseRepository<Alert> {
  constructor(adapter: StorageAdapter) {
    super(adapter, COLLECTION, DATE_FIELDS);
  }

  /** All alerts attached to a specific purchase. */
  async getByPurchaseId(purchaseId: string): Promise<Alert[]> {
    const alerts = await this.loadAll();
    return alerts.filter((alert) => alert.purchaseId === purchaseId);
  }

  /** All unread alerts, ordered so the soonest-firing comes first. */
  async getUnread(): Promise<Alert[]> {
    const alerts = await this.loadAll();
    return alerts
      .filter((alert) => !alert.isRead)
      .sort((a, b) => a.alertDate.getTime() - b.alertDate.getTime());
  }

  /** Convenience — flip `isRead` to true. */
  async markAsRead(id: string): Promise<Alert | null> {
    return this.update(id, { isRead: true });
  }
}
